import { CheckCircleIcon, MailIcon } from 'lucide-react';
export function Flyer() {
  return <div className="max-w-4xl mx-auto px-8 py-12 bg-white min-h-screen">
      <div className="mb-12">
        <img src="./Light.png" alt="Legion Logo" className="h-32 mb-8" />
        <h1 className="text-3xl md:text-4xl font-bold mb-6 text-[#4A0D42]">
          Become a Legion Founding Partner: Shape the Future of Litigation
          Drafting & Earn Significant Rewards
        </h1>
      </div>
      <div className="space-y-12">
        <section>
          <h2 className="text-2xl font-bold mb-4 text-[#4A0D42]">
            The Challenge:
          </h2>
          <p className="text-gray-700">
            Drafting standard litigation documents – pleadings, discovery
            requests, motions – consumes countless hours for litigators,
            especially in small to medium-sized firms. This repetitive work
            drains valuable time that could be spent on strategy, client
            interaction, and growth.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4 text-[#4A0D42]">
            The Solution: Legion - The AI-Powered Drafting Assistant for
            Litigators
          </h2>
          <p className="text-gray-700 mb-6">
            Legion is building an intelligent, in-browser drafting platform
            designed specifically for US litigation attorneys. We leverage AI to
            help lawyers draft high-quality pleadings, discovery, and motions
            faster and more accurately.
          </p>
          <div className="grid md:grid-cols-2 gap-6 bg-gray-50 p-6 rounded-lg">
            <div>
              <h3 className="font-semibold mb-2 text-[#4A0D42]">
                Current Focus:
              </h3>
              <p className="text-gray-700">
                California, New York, Florida, and Illinois Civil & Probate
                Litigation (State Court)
              </p>
            </div>
            <div>
              <h3 className="font-semibold mb-2 text-[#4A0D42]">Launched:</h3>
              <p className="text-gray-700">AI-Powered Complaint Builder</p>
            </div>
            <div>
              <h3 className="font-semibold mb-2 text-[#4A0D42]">
                Coming Soon:
              </h3>
              <p className="text-gray-700">
                Contention ROGs Builder, Full Discovery Suite (SROGs, RFPs,
                RFAs)
              </p>
            </div>
            <div>
              <h3 className="font-semibold mb-2 text-[#4A0D42]">Pricing:</h3>
              <p className="text-gray-700">
                Simple & Accessible - $10/page usage-based pricing.
              </p>
            </div>
          </div>
        </section>
        <section className="bg-[#4A0D42] text-white p-8 rounded-lg">
          <h2 className="text-2xl font-bold mb-6">
            Introducing the Exclusive Legion Founding Partner Program
          </h2>
          <p className="text-gray-100 mb-6">
            We're looking for forward-thinking consultants, MSPs, and legaltech
            providers who serve law firms in CA, NY, FL, and IL to join our
            exclusive Founding Partner Program.
          </p>
          <div className="space-y-6">
            <div>
              <h3 className="text-xl font-semibold mb-3">
                Generous Commission
              </h3>
              <p className="text-gray-100">
                Receive 40% of the gross usage revenue generated by each new law
                firm you refer to Legion.
              </p>
            </div>
            <div>
              <h3 className="text-xl font-semibold mb-3">
                Significant Payout Potential
              </h3>
              <p className="text-gray-100">
                Earn commissions until the referred firm reaches $6,000 USD in
                total lifetime spend with Legion, resulting in a maximum payout
                of $2,400 USD per referred client!
              </p>
            </div>
            <div>
              <h3 className="text-xl font-semibold mb-3">
                Long-Term Alignment
              </h3>
              <p className="text-gray-100">
                You benefit directly as your referred clients adopt Legion and
                increase their usage over time, fueled by our expanding product
                features.
              </p>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-6 text-[#4A0D42]">
            Why Partner with Legion Now?
          </h2>
          <div className="space-y-4">
            {['Lucrative Founding Terms: Lock in our most generous commission structure, designed specifically for early partners.', 'Offer Innovation: Provide your clients with a cutting-edge AI tool that directly addresses drafting pain points.', 'Differentiate Your Services: Stand out by introducing valuable, efficiency-boosting technology.', 'Early Influence: Be among the first to partner and provide feedback as we rapidly develop new features.'].map((benefit, i) => <div key={i} className="flex items-center gap-3">
                <CheckCircleIcon className="h-6 w-6 text-[#4A0D42]" />
                <span className="text-gray-700">{benefit}</span>
              </div>)}
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-6 text-[#4A0D42]">
            Benefits for Your Clients:
          </h2>
          <div className="space-y-4">
            {['Draft Faster: Significantly reduce time spent on repetitive drafting tasks using Legion.', 'Improve Quality: Leverage AI for more consistent and accurate documents.', 'Focus on Strategy: Free up attorney time for higher-value legal work.', 'Accessible Pricing: Pay-as-you-go model fits small/medium firm budgets.'].map((benefit, i) => <div key={i} className="flex items-center gap-3">
                <CheckCircleIcon className="h-6 w-6 text-[#4A0D42]" />
                <span className="text-gray-700">{benefit}</span>
              </div>)}
          </div>
        </section>
        <section className="border-t border-gray-200 pt-8">
          <div className="text-center">
            <h2 className="text-2xl font-bold mb-4 text-[#4A0D42]">
              Ready to Shape the Future and Reap the Rewards?
            </h2>
            <p className="text-gray-700 mb-6">
              Help bring the power of AI drafting to litigators with Legion and
              earn substantial commissions. Let's discuss how we can partner
              together.
            </p>
            <div className="inline-flex items-center text-[#4A0D42]">
              <MailIcon className="h-5 w-5 mr-2" />
              <a href="mailto:zihao@legion.law" className="text-lg font-medium hover:underline">
                zihao@legion.law
              </a>
            </div>
            <p className="text-sm text-gray-500 mt-6">
              *The Legion Founding Partner Program terms and conditions are
              subject to a formal partnership agreement.
            </p>
          </div>
        </section>
      </div>
    </div>;
}
